# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!

target 'products' do
    pod 'Fabric'
    pod 'Crashlytics'
    
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'SDVersion'
    pod 'Masonry'
    
    pod 'UIAlertController+Blocks'
    pod 'HMSegmentedControl'
    pod 'SDWebImage', '~>3.8'
end
